export const resumeKeywords = [

  "Mohd Sanib",
  "Mohd Sanib resume",
  "Mohd Sanib CV",
  "Software Developer",
  "Full Stack Developer",
  "Frontend Developer",
  "Backend Developer",
  "Web Developer",
  "Student Developer",
  "Junior Developer",
  "Entry Level Developer",
  "Computer Science Graduate",
  "B.Tech Computer Science",
  "Lovely Professional University",
  "LPU",


  "JavaScript",
  "TypeScript",
  "Python",
  "Java",
  "C++",
  "C Programming",
  "HTML5",
  "CSS3",
  "SQL",
  "NoSQL",


  "React.js",
  "Next.js",
  "React Native",
  "Vue.js",
  "Angular",
  "Tailwind CSS",
  "Bootstrap",
  "ShadCN UI",
  "Material UI",
  "Framer Motion",
  "SCSS",
  "CSS Modules",
  "Responsive Design",
  "Mobile First Design",
  "Cross Browser Compatibility",
  "Progressive Web Apps",
  "PWA",
  "Single Page Applications",
  "SPA",


  "Node.js",
  "Express.js",
  "Next.js API Routes",
  "RESTful APIs",
  "GraphQL",
  "WebSockets",
  "Microservices",
  "Serverless Functions",
  "API Design",
  "API Integration",
  "Authentication",
  "Authorization",
  "JWT",
  "OAuth",


  "MongoDB",
  "PostgreSQL",
  "MySQL",
  "Oracle Database",
  "SQLite",
  "Redis",
  "Firebase Firestore",
  "Prisma ORM",
  "Drizzle ORM",
  "Database Design",
  "Data Modeling",
  "Database Optimization",
  "ACID Properties",
  "Database Indexing",


  "AWS",
  "Google Cloud Platform",
  "Microsoft Azure",
  "Vercel",
  "Netlify",
  "Firebase",
  "Docker",
  "Kubernetes",
  "CI/CD",
  "GitHub Actions",
  "Jenkins",
  "Git",
  "GitHub",
  "GitLab",
  "Version Control",
  "Deployment",
  "Cloud Computing",
  "Serverless Architecture",


  "Machine Learning",
  "Deep Learning",
  "Neural Networks",
  "Natural Language Processing",
  "NLP",
  "Computer Vision",
  "TensorFlow",
  "PyTorch",
  "Keras",
  "scikit-learn",
  "BERT",
  "LSTM",
  "LLaMA",
  "Large Language Models",
  "LLM",
  "Generative AI",
  "ChatGPT API",
  "OpenAI API",
  "Hugging Face",
  "LangChain",
  "Prompt Engineering",
  "AI Model Training",
  "Data Science",
  "Data Analysis",


  "Unit Testing",
  "Integration Testing",
  "End-to-End Testing",
  "Test Driven Development",
  "TDD",
  "Jest",
  "Cypress",
  "Playwright",
  "React Testing Library",
  "Postman",
  "API Testing",
  "Bug Tracking",
  "Quality Assurance",
  "Code Review",
  "Debugging",


  "Agile Development",
  "Scrum",
  "Kanban",
  "Object Oriented Programming",
  "OOP",
  "Functional Programming",
  "Clean Code",
  "SOLID Principles",
  "Design Patterns",
  "MVC Architecture",
  "System Design",
  "Scalable Architecture",
  "Performance Optimization",
  "Code Optimization",
  "Refactoring",
  "Technical Documentation",


  "Data Structures",
  "Algorithms",
  "Big O Notation",
  "Arrays",
  "Linked Lists",
  "Stacks",
  "Queues",
  "Trees",
  "Graphs",
  "Hash Tables",
  "Sorting Algorithms",
  "Searching Algorithms",
  "Dynamic Programming",
  "Recursion",
  "Problem Solving",


  "Visual Studio Code",
  "VS Code",
  "IntelliJ IDEA",
  "Eclipse",
  "Sublime Text",
  "Vim",
  "Webpack",
  "Vite",
  "Babel",
  "ESLint",
  "Prettier",
  "npm",
  "yarn",
  "pnpm",


  "Problem Solving",
  "Critical Thinking",
  "Team Collaboration",
  "Communication Skills",
  "Leadership",
  "Project Management",
  "Time Management",
  "Adaptability",
  "Self-Motivated",
  "Detail Oriented",
  "Analytical Thinking",
  "Creative Problem Solving",
  "Continuous Learning",
  "Mentoring",
  "Code Review",


  "Internship",
  "Entry Level",
  "Junior Developer",
  "Software Development Trainee",
  "Open Source Contributor",
  "Freelance Developer",
  "Project Based Work",
  "Team Projects",
  "Solo Projects",
  "Academic Projects",
  "Personal Projects",
  "Portfolio Projects",


  "HackerRank Certificate",
  "FreeCodeCamp Certificate",
  "AMCAT Certificate",
  "Technical Certifications",
  "Programming Competitions",
  "Coding Challenges",
  "GitHub Contributions",
  "Open Source Contributions",


  "Web Applications",
  "Mobile Applications",
  "Desktop Applications",
  "E-commerce Platform",
  "Portfolio Website",
  "Blog Platform",
  "Social Media App",
  "Chat Application",
  "Task Management System",
  "Content Management System",
  "CMS",
  "API Development",
  "Microservices",
  "Real-time Applications",
  "Data Visualization",
  "Machine Learning Projects",
  "AI Projects",


  "Bhubaneswar",
  "Odisha",
  "India",
  "Remote Work",
  "Hybrid Work",
  "Full Time",
  "Part Time",
  "Contract",
  "Internship",
  "Available Immediately",
  "Flexible Schedule",


  "Computer Science",
  "Software Engineering",
  "Information Technology",
  "Bachelor of Technology",
  "B.Tech",
  "Engineering Student",
  "Final Year Student",
  "Academic Excellence",
  "Technical Skills",
  "Coursework",
  "Capstone Project",


  "Digital Transformation",
  "Innovation",
  "Technology Solutions",
  "Software Solutions",
  "Business Intelligence",
  "User Experience",
  "UX",
  "User Interface",
  "UI",
  "Cross-functional Teams",
  "Stakeholder Management",
  "Requirements Analysis",
  "Technical Specifications",
  "Code Documentation",
  "Best Practices",
];
